spring:
  jwt:
    secret: ENC(LZfRkimWUcofW+0DbAkzqIsZak4F82V8Vm3VScQoJTLvpdub5TPfeeMrA4Nq7HMtXsBf/+UXJdI=)

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ENC(ao/asGULsC0FZZVz57VlLnKKg984D//awkZrJg05n5q1Rzb9230bWOmcNcThzhJO4Yh0Qz9rf1maEwQP2z6g1dllMXY1AmG9xrLR9qU9z/A0dirAEw50Og==)
            client-secret: ENC(ng8tvFKUirorpAgXqzGMctT4CBgpNDGSPyTSQJKzNVo9jaU5ZPjZ3KjPdLiX26LM)
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/moaolio?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
