server:
  port: 8080

# ?? ??? ??
google:
  client:
    clientId: your_google_client_id
    clientSecret: your_google_client_secret
  redirectUri: http://localhost:8080/login/google

# ??? ??? ??
kakao:
  client:
    clientId: your_kakao_client_id
    clientSecret: your_kakao_client_secret
  redirectUri: http://localhost:8080/login/kakao

# ??? ??? ??
naver:
  client:
    clientId: your_naver_client_id
    clientSecret: your_naver_client_secret
  redirectUri: http://localhost:8080/login/naver

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.clientId}
            client-secret: ${google.client.clientSecret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          kakao:
            client-id: ${kakao.client.clientId}
            client-secret: ${kakao.client.clientSecret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email
          naver:
            client-id: ${naver.client.clientId}
            client-secret: ${naver.client.clientSecret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
  datasource:
    url:
    username: root
    password: 1234
    driver-class-name:

  jpa:
    database: mysql

  mvc:

  mail: